### ISSUE TITLE
ارور در دسته بندی

### ISSUE THREAD

**Issue by Meysamhb** [sayyah/ECommerce#406]
با کاربر superadmin وارد سایت می شوم
از مسیر ذیل اقدام به ایجاد دسته بندی میکنم
مدیریت>>>دسته بندی و محصولات>>>دسته بندی

بعد از پر کردن موارد خواسته شده و هنگام زدن دکمه "ثبت" با ارور مواجه می شوم

![Image](https://github.com/sayyah/ECommerce/assets/92229790/d24ed98e-bf5a-4eb0-ad02-97e775edfe06)

همچنین اگر هر کدام از موارد خواسته شده به غیر از نام را مقداردهی نکنم با ارور مواجه می شوم

**Comment by Meysamhb** [comment]
بعد از رفتن به قسمت دسته بندی،اقدام به ایجاد دسته بندی جدید می کنم،در مرحله اول عکس را وارد نمی کنم،پیغامی مبنی بر وارد کردن عکس می دهد،بعد عکس را بارگذاری می کنم،دکمه ی ثبت را می زنم و ارور مطابق عکس ذیل نمایش داده می شود

![Image](https://github.com/sayyah/ECommerce/assets/92229790/7ec821c2-2ac2-40e1-9894-78ac38147206)

**Comment by AliMozafari67** [comment]
approve

**Comment by AliMozafari67** [comment]
Rebase Done

**Comment by AliMozafari67** [comment]
تسک اشتباه close شد

**Comment by AliMozafari67** [comment]
مشکلات برطرف شد

**Comment by AliMozafari67** [comment]
مشکلات برطرف شد
