### ISSUE TITLE
ProductAttributeGroup

### ISSUE THREAD

**Issue by fadaeimehdi** [sayyah/ECommerce#470]

**Comment by sayyah** [comment]
چرا pr نداره؟

**Comment by AliMozafari67** [comment]
pr ارسال شد

**Comment by sayyah** [comment]
کجا ارسال شد؟


![Image](https://github.com/sayyah/ECommerce/assets/16479025/c90e04ca-41ac-4d61-b70b-07c0a9cf4839)
