### ISSUE TITLE
چک کردن سبد خرید - بک اند

### ISSUE THREAD

**Issue by pouryapb** [sayyah/ECommerce#520]
https://github.com/sayyah/ECommerce/blob/7e7f0f4c10af02fccbd1c3c5b6a54de7f888fc3e/ECommerce.Front.BolouriGroup/Pages/Shared/_Layout.cshtml#L528

**Comment by Meysamhb** [comment]
لطفا قبل از زدن تسک با من هماهنگ کنید و یا توضیحی برای تسکی که می زنید بنویسید
برای این مورد هم هیچ توضیحی داده نشده و قابل تست نیست

**Comment by pouryapb** [comment]
> لطفا قبل از زدن تسک با من هماهنگ کنید و یا توضیحی برای تسکی که می زنید بنویسید
> برای این مورد هم هیچ توضیحی داده نشده و قابل تست نیست

#483
@Meysamhb مربوط به این تسک

**Comment by Meysamhb** [comment]
مشکل همچنان برقرار است و رفع نشده

@AliMozafari67

**Comment by sayyah** [comment]
@Meysamhb please "UserCode": "15", at the end of AppSetting file in the API project

**Comment by Meysamhb** [comment]
@AliMozafari67 
@sayyah 

کد فوق جایگذاری شد اما همچنان مشکل برقرار است

**Comment by AliMozafari67** [comment]
Approve

**Comment by AliMozafari67** [comment]
Rebase Don

**Comment by Meysamhb** [comment]
در این برنچ 
1- امکان ساخت یک یوزر جدید نیست
2-مقدار موجودی به روز نیست،یعنی تعداد فروخته شده از یک کالا از مجموع کالا در دیتابیس کسر نمیگردد
3- چک شود حتما قبل از رفتن به درگاه پرداخت اگر موجودی یک کالا تمام شد پیغام دهد،نه اینکه به دگاه پرداخت رفته پول از حساب کاربر کم شده و بعد پیغام دهد با پشتیبانی تماس گرفته شود

@AliMozafari67

**Comment by Meysamhb** [comment]
Please Approve
@sayyah 
@pouryapb 
@SamanR86
