### ISSUE TITLE
ایجاد Mapper

### ISSUE THREAD

**Issue by AliMozafari67** [sayyah/ECommerce#524]
ایجاد DTO در لایه application و پیاده سازی Mapper  برای Color Entity

**Comment by Meysamhb** [comment]
Please resolve conflicts 

@SamanR86

**Comment by Meysamhb** [comment]
@sayyah 
@AliMozafari67 
@pouryapb 
Approve

**Comment by Meysamhb** [comment]
تسک ارور دارد
و پروژه DTO در آن وجود ندارد

@SamanR86

**Comment by sayyah** [comment]
@SamanR86 
مپ کردن dto به entity

**Comment by sayyah** [comment]
@SamanR86 
حذف مپر از پروژه بلوری و سرویس انجام شد؟

**Comment by SamanR86** [comment]
سرویس که ارجاع نداشت
بلوری حدف شد

**Comment by SamanR86** [comment]
مپر اصلاح شد

**Comment by SamanR86** [comment]
GetQueryDto is done.

**Comment by Meysamhb** [comment]
ادغام با تسک 663
@sayyah
