### ISSUE TITLE
مشکل در مرتب سازی بر اساس ویژگی

### ISSUE THREAD

**Issue by Meysamhb** [sayyah/ECommerce#535]
یک کالا را سرچ می کنم
لیستی از محصولات مرتبط نمایش داده می شود
از قسمت مرتب سازی بر اساس ویژگی یکی از آیتم ها را انتخاب می کنم
به عنوان مثال : ارزانترین
انتظار می رود که تمام کالاهای نمایش داده شده را به درستی مرتب کند که در عمل این اتفاق نمی افتد 
و هیچ کدام از موارد مرتب سازی درست عمل نمی کند

لازم به ذکر است 
مرتب سازی بر اساس ویژگی در صفحه ی shop  و دسته بندی ها به درستی کار می کند و تنها در زمانی که یک جستجو انجام می دهیم در نتایج جستجو این آیتم دچار اختلال می شود

**Comment by Meysamhb** [comment]
conflict رفع شود و آقا سامان approve کند

**Comment by Meysamhb** [comment]
@SamanR86 
@sayyah 
please Approve

**Comment by Meysamhb** [comment]
مرتب سازی بر اساس آیتم های موجود روی موارد ذیل اعمال نمی شود 

وقتی روی برندهای پایین صفحه کلیک می کنیم نتایج حاصل از آن نمایش داده می شود مرتب سازی انجام نمی شود

وقتی بر اساس کد هلو سرچ می کنیم و نتایج حاصل از آن نمایش داده می شود مرتب سازی انجام نمی شود


@AliMozafari67

**Comment by AliMozafari67** [comment]
منظور از برندهای پایین صفحه  کجاست؟

**Comment by Meysamhb** [comment]
![Image](https://github.com/sayyah/ECommerce/assets/92229790/6aaed8f7-5224-4c76-9f35-d980886a5914)

**Comment by AliMozafari67** [comment]
Approve

**Comment by AliMozafari67** [comment]
Rebase Done
