### ISSUE TITLE
درصفحه لاگین امکان تایپ عدد انگلیسی وجود ندارد 

### ISSUE THREAD

**Issue by alyereza** [sayyah/ECommerce#539]
امکان تایپ عدد انگلیسی در رمز عبور و تکرار رمز در صفحه لاگین وجود ندارد

1. ورود کاربر جدید
2. وارد کردن شماره و کد پیامک شده
3. پر کردن موارد خواسته شده در صفحه ورود
4. اعداد وارد شده در رمز انگلیسی نمایش داده میشوند و اجازه ثبت توسط سایت داده نمیشود
*********************از رمز هایی که قبلا استفاده کردید استفاده نکنید**********************

رفتار مورد انتظار :با تغییر کیبورد به انگلیسی اعداد به انگلیسی وارد شوند

**Comment by pouryapb** [comment]
با انجام مراحل گفته شده، مشکلی بوجود نیامد و ثبت انجام شد

**Comment by pouryapb** [comment]
@sayyah

**Comment by pouryapb** [comment]
[علت احتمالی مشکل](https://stackoverflow.com/questions/65890162/entity-framework-6-sql-server-triggers-getting-error)
@sayyah چون مربوط به دیتابیس هستش شما یه نگاه بندازین

**Comment by pouryapb** [comment]
[احتمالا مشکل از آپدیت EF هستش](https://stackoverflow.com/questions/65890162/entity-framework-6-sql-server-triggers-getting-error)
