### ISSUE TITLE
نام نویسنده

### ISSUE THREAD

**Issue by Meysamhb** [sayyah/ECommerce#554]
با کاربر superadmin  وارد بخش مدیریت می شوم
مسیر ذیل را دنبال می کنم
مقالات وبلاگ و آموزش ها>>نویسنده>>ایجاد نویسنده جدید

دو مقدار اول با عناوین " نام " و "نام انگلیسی" می باشد

در قسمت نام انگلیسی با فونت فارسی هم می توان این مقدار را پر کرد

انتظار می رود
1- عنوان "نام" به "نام فارسی" تغییر عنوان پیدا کند
2-در کادر"نام انگلیسی" تنها اجازه ورود کاراکترهای انگلیسی داده شود

**Comment by AliMozafari67** [comment]
تعداد کامیت ها بیشتر از یکی می باشد
