### ISSUE TITLE
ارور در هنگام حذف مقاله

### ISSUE THREAD

**Issue by Meysamhb** [sayyah/ECommerce#556]
در قسمت مدیریت وقتی میخواهیم یک مقاله را حذف کنیم اروری با عنوان ذیل ظاهر می شود
"به علت وابستگی با عناصر دیگر امکان حذف وجود ندارد"

**Comment by AliMozafari67** [comment]
این تسک وابسته به تسک 599 می باشد و بعد از merge شدن 599 انجام خواهد شد

**Comment by AliMozafari67** [comment]
با تسک 603 یکی می باشد

**Comment by Meysamhb** [comment]
لطفا قبل از 
Approve 
کردن به قسمت تست منتقل نشود

@sayyah

**Comment by sayyah** [comment]
@Meysamhb Approved
