### ISSUE TITLE
مشکل در ثبت کامنت برای محصولات

### ISSUE THREAD

**Issue by AliMozafari67** [sayyah/ECommerce#560]
زمانی که قصد ثبت کامنت برای یک محصول را داریم در صورتی که نام محصول در نوار آدرس به درستی نمایش داده نشود ، ثبت انجام نمی شود
خطای کد جاوااسکریپت

**Comment by pouryapb** [comment]
یعنی چی؟؟

**Comment by pouryapb** [comment]
رمزگشایی کردم فهمیدم یعنی چی...

**Comment by Meysamhb** [comment]
@AliMozafari67 
@pouryapb 

در چه مواردی این ارور رخ می دهد
لطفا جهت تست توضیح کامل را بنویسید

**Comment by pouryapb** [comment]
@Meysamhb
کالا هایی که در url [مقادیر غیر مجاز](https://developer.mozilla.org/en-US/docs/Glossary/Percent-encoding) دارند باعث این مشکل میشود.

**Comment by AliMozafari67** [comment]
مثل قبلی😁
