### ISSUE TITLE
مشکل در ثبت کامنت برای وبلاگ

### ISSUE THREAD

**Issue by AliMozafari67** [sayyah/ECommerce#561]
زمانی که قصد ثبت کامنت برای یک وبلاگ را داریم در صورتی که نام وبلاگ در نوار آدرس به درستی نمایش داده نشود ، ثبت انجام نمی شود
خطای کد جاوااسکریپت

**Comment by Meysamhb** [comment]
@AliMozafari67 
@pouryapb 

در چه مواردی این ارور رخ می دهد
لطفا جهت تست توضیح کامل را بنویسید

**Comment by pouryapb** [comment]
@Meysamhb
کالا هایی که در url [مقادیر غیر مجاز](https://developer.mozilla.org/en-US/docs/Glossary/Percent-encoding) دارند باعث این مشکل میشود.

**Comment by AliMozafari67** [comment]
در نوار آدرس اگه اسم محصول به صورت صحیح نشان داده نشود امکان ثبت کامنت برای آن محصول نیست
