### ISSUE TITLE
حذف اطلاعات محرمانه

### ISSUE THREAD

**Issue by AliMozafari67** [sayyah/ECommerce#570]
با توجه به public شدن پروژه نیاز است یکسری از اطلاعات از پروژه حذف شوند

انتظار می رود افرادی که به پروژه دسترسی پیدا می کنند نتوانند به اطلاعاتی از جمله اطلاعات کاربری، EncryptKey و ... دسترسی داشته باشند

لطفا توضیح دهید چه اطلاعاتی را از پروژه حذف نمودید که اعضای تیم در جریان کار قرار بگیرند

**Comment by Meysamhb** [comment]
Please resolve conflicts and Rebase

@pouryapb
