### ISSUE TITLE
Implement the unit of work interface

### ISSUE THREAD

**Issue by sayyah** [sayyah/ECommerce#582]
**Describe the solution you'd like**
We have to implement the 'Unit of work' interface and delete 'SaveContext' from 'AsynceRepository'. We have to save 'Sunflower' and 'Holoo' database in one method with together.

**Comment by Meysamhb** [comment]
حذف در تمام زیر دسته های قسمت مدیریت اعم از "دسته بندی و محصولات" و ... با اشکال مواجه است و اگر قصد حذف یک مورد را داشته باشیم پیغام "به علت وابستگی با عناصر دیگر امکان حذف وجود ندارد" نمایش داده می شود
@sayyah

**Comment by Meysamhb** [comment]
در قسمت مدیریت >>دسته بندی و محصولات >> محصولات 
اگر بخواهسم یک محصول ایجاد کنیم با پیغام ذیل مواجه می شویم




![Image](https://github.com/sayyah/ECommerce/assets/92229790/2c9bddac-676d-4e1a-9bc4-434599019ed1)

**Comment by Meysamhb** [comment]
در قسمت مدیریت>>مقاله وبلاگ و آموزش ها>>مقالات

اگر بخواهیم یک مقاله ایجاد کنیم با ارور زیر مواجه می شویم



![Image](https://github.com/sayyah/ECommerce/assets/92229790/ba1b783a-8d47-4a5b-a0a9-90b9f6cd93fc)


@sayyah

**Comment by Meysamhb** [comment]
کاربر superadmin  را شناسایی نمی کند و موقع ورود پیغام زیر ظاهر می شود



![Image](https://github.com/sayyah/ECommerce/assets/92229790/d114b8fd-478c-4e3f-a8c6-a50d5ad7f347)



@sayyah

**Comment by Meysamhb** [comment]
در تست مجدد برای کاربران دیگر متوجه این موضوع شدم که هیچ کاربری را شناسایی نمیکند با اینکه در دیتابیس موجود است
به قصد تست یک کاربر که وجود داشت را دوباره تست ثبت نام کردم که با ارور زیر مواجه شدم


![Image](https://github.com/sayyah/ECommerce/assets/92229790/0639ef14-5d38-463b-88d4-9148b455c38a)

@sayyah

**Comment by Meysamhb** [comment]
بدون ورود به یوزر نیم قصد ارسال کامنت از طریق صفحه ی تماس با ما را داشتم که با ارور زیر مواجه شدم



![Image](https://github.com/sayyah/ECommerce/assets/92229790/0cdc09fe-c06d-48b7-a56f-720a3754ae75)

@sayyah

**Comment by Meysamhb** [comment]
در قسمت مدیریت <<اسلاید شو و تنظیمات دیگر<<اسلاید شو وقتی میخواهیم یک مورد اضافه کنیم،اگر هیچ مرودی را وارد نکنیم و ثبت را بزنیم با ارور زیر مواجه می شویم 

![Image](https://github.com/sayyah/ECommerce/assets/92229790/5025a028-2c93-440a-b554-4d7b5f4afb8b)

همچنین امکان ایجاد اسلایو شو جدید وجود ندارد،بدین صورت که بعد از تکمیل موارد خواسته شده هیج اسلاید شوی جدیدی ایجاد نمی شود و هیچ اروری هم نمایش داده نمی شود

**Comment by Meysamhb** [comment]
خطا در هنگام ورود با کاربر سوپرادمین


![Image](https://github.com/sayyah/ECommerce/assets/92229790/d36a16f7-100e-4bb9-8cc6-7a43f647310a)

@sayyah

**Comment by Meysamhb** [comment]
عدم ارسال کد یک بار مصرف برای ورود به حساب کاربری

@sayyah

**Comment by sayyah** [comment]
اشکالات اصلاح شد و push کردم

**Comment by Meysamhb** [comment]
هنگامی که می خواهیم نظرات مربوط به یک کالا را تایید کنیم ،بعد از زدن دکمه تایید،با ارور مواجه می شویم

**Comment by sayyah** [comment]
@Meysamhb I pushed, please fetch and rebase new changes

**Comment by Meysamhb** [comment]
> در قسمت ایجاد تخفیف بر اساس فاکتور اگر بخواهیم هر کدام از تخفیف های ایجاد شده را ویرایش کنیم به ارور بر می خوریم ،بدین ترتیب که : 1 - اگر بخواهیم نام را تغییر دهیم،اروری با مضمون "اشکال در سمت سرور " مواجه می شویم 2 - اگر بخواهیم کد تخفیف را ویرایش کنیم و تغییر دهیم، اروری با مضمون "نام تخفیف تکراری است" مواجه می شویم

ویرایش غیرفعال شده است،لطفا این مورد رفع گردد
