### ISSUE TITLE
نمایش کالای بدون قیمت

### ISSUE THREAD

**Issue by Meysamhb** [sayyah/ECommerce#593]
کالای بدون قیمت در صفحه shop نمایش داده نمی شود ،اما اگر آدرس آن کالا را در آدرس بار وارد کنیم کالا نمایش داده می شود
که انتظار می رود این موضوع مرتفع گردد

**Comment by pouryapb** [comment]
لطفا متن های تسک ها رو واضح تر بنویسید. من ۲ تا برداشت دارم از "مرتفع شدن":
۱. آدرس کالا وارد شد نشون داده نشه
۲. داخل صفحه shop کالا ها نشون داده بشه
