### ISSUE TITLE
نمایش عدم موجودی

### ISSUE THREAD

**Issue by Meysamhb** [sayyah/ECommerce#594]
کالاهایی که به موجودی آنها تمام می شود در ذیل آن باید متن "عدم موجودی " نمایش داده شود که اکنون اینطور نیست
به طور مثال یک کالا را انتخاب کرده و به اندازه موجودی به سبد خرید اضافه کنید و خرید را تکمیل کنید

اکنون دوباره به صفحه ی همان کالا بروید
افزودن به سبد خرید را که می زنیم عبارت "تعداد انتخابی کالا بیشتر از موجودی است" نمایش داده می شود
که انتظار می رود برای تمام کالاهایی که موجودی ندارند عبارت " عدم موجودی " ذکر شود

**Comment by sayyah** [comment]
@Meysamhb 
این مورد یافت نشد

**Comment by Meysamhb** [comment]
این مورد با رفع مشکل مربوط به سبد خرید حل شد
