### ISSUE TITLE
عدم تطابق موجودی کالا در دیتا بیس و تعداد انتخابی کالا

### ISSUE THREAD

**Issue by Meysamhb** [sayyah/ECommerce#595]
کالای A در انبار نمایشگاه 2 عدد و انبار چوکام 20 عدد یعنی جمعا 22 عدد موجود است
از این کالا من 22 عدد یعنی تمام موجودی را به سبد خرید اضافه کرده و خرید را نهایی می کنم و اگر بخواهم یک عدد دیگر اضافه کنم پیغام "تعداد انتخابی کالا بیشتر از موجودی است" نمایش داده می شود.

قاعدتا وقتی دوباره به این کالا مراجعه می کنم نباید اجازه اضافه کردن به سبد خرید را به من بدهد چون پیغام اتمام موجودی نمای شداده شده و در دیتابیس هم موجودی ندارد
اما من می توانم به تعدادی که در انبار نمایشگاه موجود است دوباره به سبد خرید اضافه کنم 
یعنی اگر 2 عدد باشد می توانم 2 عدد و 10 عدد هم باشد 10 عدد از مجموع موجودی کالای مورد نظر بیشتر سفارش دهم و اگر بیشتر از تعداد موجودی نمایشگاه قصد خرید داشته باشم پیغام "تعداد انتخابی کالا بیشتر از موجودی است" نمایش داده می شود

**Comment by AliMozafari67** [comment]
در تسک 520 مشکل حل شده است
