### ISSUE TITLE
دسته بندی و محصولات

### ISSUE THREAD

**Issue by Meysamhb** [sayyah/ECommerce#600]
در قسمت مدیریت >>دسته بندی و محصولات>>دسته بندی

  امکان ایجاد دسته بندی جدید و ویرایش موارد موجود در این قسمت وجود ندارد و با ارور زیر مواجه می شویم

![Image](https://github.com/sayyah/ECommerce/assets/92229790/d48c0804-72c5-4a69-b110-5c6fc364c959)

**Comment by AliMozafari67** [comment]
در تسک 406 این مشکل حل شده است

**Comment by Meysamhb** [comment]
Linked pull requests مربوط به تسک 406 به اشتباه در issue درج شده 
لطفا اطلاعات درست را وارد کرده و بعد از آن Approve  انجام شود 
@sayyah 
@AliMozafari67

**Comment by AliMozafari67** [comment]
من که نفهمیدم چی نوشتید!

**Comment by Meysamhb** [comment]
بخاطر باهم بودن فونت فارسی و انگلیسی اینطور شد
![Capture](https://github.com/sayyah/ECommerce/assets/92229790/b419891d-686d-4d5f-8480-ac69c11fe852)
@AliMozafari67

**Comment by Meysamhb** [comment]
لینک درست به تسک 406 داده نشده
و از طرفی تسک 406 در لیست پی آر موجود است
که Approve نشده

لطفا این موارد را اصلاح کنید

@AliMozafari67

**Comment by AliMozafari67** [comment]
اصلاح شد

**Comment by Meysamhb** [comment]
@sayyah 
@pouryapb 
Approve

**Comment by Meysamhb** [comment]
جهت ویرایش بعد از ایجاد تغییرات هیچ تغییری اعمال نمی شود و عملا این گزینه اصلاح نشد 

همچنین بعد از زدن دکمه ی ویرایش لیست انتخاب "منوی پدر"  جهت تغییر به کاربر نمایش داده شود، در حال حاضر تنها آدرس مسیر نمایش داده می شود

@AliMozafari67

**Comment by AliMozafari67** [comment]
موارد اصلاح شد
بر اساس نظر علیرضا نیاز به تغییر منوی پدر نمی باشد
