### ISSUE TITLE
ایجاد و حذف مقاله

### ISSUE THREAD

**Issue by Meysamhb** [sayyah/ECommerce#603]
در قسمت مدیریت>>مقالات وبلاگ و آموزش ها >> مقالات >>ایجاد مقاله جدید وقتی اقدام به ایجاد مقاله می کنیم و موارد خواسته شده را پر میکنیم ، مقاله جدید ایجاد نمی شود

همچنین وقتی قصد حذف کردن یک مقاله را داریم "به علت وابستگی با عناصر دیگر امکان حذف وجود ندارد" نمایش داده می شود

**Comment by AliMozafari67** [comment]
همان تسک 556 می باشد که در حال انجام است

**Comment by Meysamhb** [comment]
در این تسک اشاره شده که امکان ایجاد مقاله وجود ندارد

**Comment by AliMozafari67** [comment]
بله در تسک 556 حل شده
