### ISSUE TITLE
ثبت مشخصات و قیمت محصولات

### ISSUE THREAD

**Issue by Meysamhb** [sayyah/ECommerce#621]
در قسمت مدیریت>>دسته بندی و محصولات>>محصولات>>ایجاد محصول جدید 
بعد از ایجاد محصول جدید در صفحه جاری نام کالا نمایش داده می شود و در ستون مقابل اقدام به مشخص کردن قیمت میکنیم
بعد از وارد کردن اطلاعات خواسته شده و مشخص کردن قیمت دکمه ثبت را می زنیم 

اتفاقی که می افتد : در همان صفحه باقی می ماند 
انتظاری که داریم : تغییرات  ثبت شده و به صفحه ای که لیست کالاها نمایش داده می شود بازگردد

این اتفاق برای ثبت "مشخصات" نیز روی می دهد و این آیتم نیز باید همانند "قیمت" اصلاح شود

**Comment by sayyah** [comment]
@Meysamhb 
لطفا از پیش نویس باگ استفاده کنید

**Comment by sayyah** [comment]
@Meysamhb 
در قسمت قیمت، لیست قیمت در پایین قرار دارد و وقتی شما قیمت جدیدی وارد میکنید در لیست پایین اضافه میشود.
علت عدم انتقال به صفحه بعد این است که کاربر بتواند به راحتی چند قیمت را وارد کند.
