### ISSUE TITLE
عدم ویرایش آدرس موجود در صفحه checkout

### ISSUE THREAD

**Issue by Meysamhb** [sayyah/ECommerce#630]
**Describe the bug**
در صفحه "چک آوت"وقتی یک آدرس وجود دارد و ما بخواهیم تغییری روی آن ایجاد کنیم،به طور مثال شهر را تغییر دهیم ،این امر امکان پذیر نمی باشد

**To Reproduce**
1-یک(چند) کالا را به سبد خرید اضافه می کنیم
2-وارد سبد خرید شده و ادامه پرداخت را می زنیم
3-در صفحه ی "چک آوت"اگر آدرسی وجود نداشته باشد روی لینک مربوطه جهت وارد کردن آدرس کلیک می کنیم اما اگر آدرسی از قبل وجود داشته باشد ،روی آن کلیک می کنیم و در حالت انتخاب قرار می دهیم و با این کار اطلاعات آن در ذیل آدرس به تفکیک نمایش داده می شود 
4- تمام سطرهای اطلاعات آدرس در حالت ویرایش قرار گرفته و می توانیم تغییر دهیم اما هیچکدام از این تغییرات اعمال نمی شود

**Expected behavior**
انتظار می رود که  وقتی بعد از انتخاب کادر آدرس در حالت ویرایش قرار می گیرد هر تغییری که کاربر انجام داد اعمال شود،برای حل این موضوع می توان دکمه ای با عنوان ثبت تغییرات در این قسمت اضافه کرد که بعد از زدن دکمه این تغییرات اعمال شود.

**Screenshots**
![777](https://github.com/sayyah/ECommerce/assets/92229790/252ad2be-a9ec-4b1f-aee4-089578504729)

**Additional context**
لازم به ذکر است اگر آدرس قبلی در حالت انتخاب قرار نگیرد می توان یک آدرس جدید اضافه کرد
اما اگر روی آن کلیک کنیم و در حالت انتخاب قرار بگیرد دیگر نمی توان آدرس جدید وارد کرد و یا اینکه از حالت انتخاب آن آدرس را خارج کرد
که این مورد هم باید رفع گردد تا بتوان با یک کلیک به حالت انتخاب یا بالعکس آن را تغییر داد

**Comment by Meysamhb** [comment]
این باگ همچنان برقرار است که به شرح چگونگی آن می پردازم

1-یک آدرس جدید به شرح عکس ذیل ایجاد می کنم


![Image](https://github.com/sayyah/ECommerce/assets/92229790/c6411f2f-b5dd-4813-9bd6-5b0a313da034)

2- پیش نمایش این آدرس در مراحل بعد در صفحه چک آوت ایجاد می شود که با کلیک روی آن و متن "اگر آدرس شما در لیست بالا وجود ندارد، لطفا برای وارد کردن آدرس جدید اینجا کلیک کنید" مقادیر این آدرس نمایش داده می شود




3- حال مقادیر را تغییر داده و دکمه ی ویرایش را می زنم و پیغام با موقیت ویرایش شد نمایش داده می شود 



![Image](https://github.com/sayyah/ECommerce/assets/92229790/9f052f99-fa58-4e8d-8525-e111f0cc15d2)

4- روی کادر پیش نمایش حاوی آدرس جدید کلیک می کنم و "اگر آدرس شما در لیست بالا وجود ندارد، لطفا برای وارد کردن آدرس جدید اینجا کلیک کنید" را انتخاب کرده تا مقادیر را دوباره چک کنم
در اینجا در آن کادر پیش نمایش تغییرات اعمال می شود اما در پایین صفحه و در کادر های مربوط به اطلاعات که ویرایش کردیم همان اطلاعات اولیه که ثبت کردیم مشاهده می شود


![Image](https://github.com/sayyah/ECommerce/assets/92229790/ced2725e-9e3e-486d-b615-49e7ec8aeee3)


یک مورد دیگر هم وجود دارد و آن اینکه وقتی باکس آدرس خالی باشد و روی ویرایش کلیک کنیم یک پیغام بدون هیچ عنوانی نمایش داده میشود که باید با پیغام مناسب نمایش داده شود به طور مثال " لطفا آدرس را وارد نمایید"

**Comment by Meysamhb** [comment]
در هنگام تغییر استان یا شهر پیغام خطا در سمت سرور نمایش داده می شود
همچنین اگر موبایل بیش از 10 رقم وارد کنیم همین ارور را نمایش می دهد

لطفا چک کلی انجام شود جهت کنترل ارورها

@pouryapb

**Comment by pouryapb** [comment]
انجام شد.

**Comment by sayyah** [comment]
کامنت گذاشتم

**Comment by pouryapb** [comment]
> کامنت گذاشتم

نمیبینمش!

**Comment by pouryapb** [comment]
انجام شد
