### ISSUE TITLE
Change tests base

### ISSUE THREAD

**Issue by sayyah** [sayyah/ECommerce#642]
**Describe the solution you'd like**
Change tests base

**Comment by sayyah** [comment]
@pouryapb 
@SamanR86 
لطفا مشکلات تست های خودتون رو در این برنچ  رفع کنید.
ممنون.
وقتی تموم شد همینجا برای من کامنت بزارید و من رو mention کنید

**Comment by pouryapb** [comment]
```diff
+ Added AutoFixture to base
+ Wishlist refactored
```
