### ISSUE TITLE
ReloadPicture

### ISSUE THREAD

**Issue by Moniy0o0** [sayyah/ECommerce#647]
**Describe the solution you'd like**
Add a default image before the main image is loaded

**Comment by Meysamhb** [comment]
نصف  تصاویر کالاها حذف شده و افکت ریلود گرفته است

![Image](https://github.com/sayyah/ECommerce/assets/92229790/ffca86bc-b547-4fa6-b6e3-2a0124b2e68b)

@Moniy0o0
