### ISSUE TITLE
Send sms with HangFire

### ISSUE THREAD

**Issue by AliMozafari67** [sayyah/ECommerce#659]
ارسال sms از طریق hangfire

این تغییر باید در بلوری انجام شود

**Comment by SamanR86** [comment]
"ConnectionStrings": {
  "LibraryBackgroundTasks": "..\\Files\\library.db"
}

کانکشن فوق باید در پروژه بلوری اضافه گردد

**Comment by sayyah** [comment]
به اشتباه با 582  مرج شده بود که من پاک کردم. دوباره PR زده بشه برای dev

همچنان با 582 باید rebase شده باشد

**Comment by sayyah** [comment]
کامیت ها رو لطفا انجام بده. ممنون

**Comment by SamanR86** [comment]
اصلاح شد
با توجه به به اینکه بخشی ازتغییرات مربوط به فایل  appsetting می باشد، لازم است این فایل در نسخه مستر اصلاح شود

**Comment by sayyah** [comment]
لطفا اطلاعات appsetting انجا اضافه بشه

**Comment by SamanR86** [comment]
@Meysamhb rebased
