### ISSUE TITLE
send Email With HangFire

### ISSUE THREAD

**Issue by AliMozafari67** [sayyah/ECommerce#660]
ارسال ایمیل از طریق hangFire

 این تغییر در باید در API انجام شود

**Comment by sayyah** [comment]
لطفا اطلاعات appsetting انجا اضافه بشه

**Comment by SamanR86** [comment]
appseting تغییری نداره

**Comment by Meysamhb** [comment]
Please Resolve Conflicts and Rebase
@SamanR86

**Comment by SamanR86** [comment]
@Meysamhb rebased
