### ISSUE TITLE
Patch 2024-01-07

### ISSUE THREAD

**Issue by sayyah** [sayyah/ECommerce#688]
[852_30414416277191.xlsx](https://github.com/sayyah/ECommerce/files/13854277/852_30414416277191.xlsx)

**Describe the solution you'd like**
اصلاح مشکلات اعلامی در فایل اکسل در تاریخ 2024-01-07

**Comment by Moniy0o0** [comment]
رفع ایرادات زیر:

1. درگاه پرداخت کار نمیکند .
2. وقتی وارد محصول میشیم در قسمت بالای صفحه عکس سر دسته نمایش داده نمیشه و عکس دیفالت نمایش داده میشه . برای مثال وارد بار سرد میشیم عکس سر دسته هست ولی یکی از محصولات رو می‌زنیم جای اون عکس عکس دیگه ای نمایش داده میشه .

قسمت زیر در Appsetting قسمت فرانت هست که باید پاک بشه ولی اگه پاک هم نشه مشکلی پیش نمیاد.
"SiteSettings": {
    "SanadSettings": {
    "terminalKey": "CSlQf8zTne2YH3mnrbwAnKx3rl9ckHKz",
    "terminalId": "24102279",
    "merchantId": "000000140341290"
  }
  },


حتما درگاه پرداخت تست بشه چون تغییر دادم.
رفتن به قسمت ادمین تست بشه

در تمام فایل ها تغییر ایجاد شده و using ها و namespace های اضافه حذف شده. این میتونه باعث مشکل بشه چون خوده سیستم حذف کرده
