### ISSUE TITLE
اصلاح سبد خرید 

### ISSUE THREAD

**Issue by Meysamhb** [sayyah/ECommerce#692]
**Describe the bug**
این باگ در محصولات با چند رنگ متفاوت و موجودی محدود مشاهده شد
**To Reproduce**
مراحل ایجاد باگ ار روی سایت اصلی بلوری ذکر می شود
1-محصول "بشقاب فلزی 35 سانت رنگی" را سرچ می کنیم
2-رنگ نارنجی این محصول 3 عدد موجودی دارد و تمام موجودی را به سبد خرید اضافه می کنیم
3-حال رنگ طوسی این محصول را انتخاب می کنیم و به سبد خرید اضافه می شود
4- در سبد خرید رنگ نارنجی را حذف می کنیم
5-مجدد وقتی می خواهیم رنگ نارنجی را به سبد خرید اضافه کنیم با این پیغام مواجه می شویم "تعداد انتخابی کالا بیشتر از موجودی است"
در حالی که این رنگ در سبد موجود نیست
6-اگر کل سبد را خالی کنیم مجدد می توانیم رنگ نارنجی را اضافه کنیم
///
1-تخته کار ارتالون 50*30 رنگی ضخامت 3 سانت را سرچ می کنم
2- دو رنگ سبد و زرد هر کدام به تعداد 3 عدد موجود است
3-طبق عکس زیر من به تعداد بیش از موجودی به سبد اضافه کردم

![2](https://github.com/sayyah/ECommerce/assets/92229790/7a927903-65f2-4671-b4ee-b8b4c51cdf04)

انتظار می رود این مورد برطرف گردیده و موارد مشابه نیز بررسی گردد.

**Comment by Meysamhb** [comment]
![Image](https://github.com/sayyah/ECommerce/assets/92229790/686b6762-c55f-4d28-a949-8a68f760a4b5)

**Comment by pouryapb** [comment]
رفع شد

**Comment by Meysamhb** [comment]
من کالای بشقاب فلزی 35 سانت رنگی را انتخاب می کنم
از رنگ نارنجی 3 عدد موجود است 
همه موجودی را به سبد خرید اضافه می کنم
اما بعد از اضافه کردن امکان کم کردن تعداد در سبد خرید وحود ندارد
مثلا نمیتوانیم با زدن منفی 3عدد را به 2 عدد کاهش دهیم مگر اینکه کالا را حذف کنیم و دوباره 2 عدد اضافه کنیم

این سناریو برای تمام کالاهای با چند رنگ و تعداد محدود صادق است 
@pouryapb

**Comment by pouryapb** [comment]
@Meysamhb میشه url این کالا رو بنویسین؟ من پیدا نمیکنم همچین کالایی رو تو نسخه خودم

**Comment by Meysamhb** [comment]
https://localhost:7173/product/%D8%A8%D8%B4%D9%82%D8%A7%D8%A8-%D9%81%D9%84%D8%B2%DB%8C35%D8%B3%D8%A7%D9%86%D8%AA


شما کلمه ی "رنگی" رو سرچ کن میاره،یا این کالا یا هر کالایی  که چند رنگ داشته باشه

@pouryapb

**Comment by pouryapb** [comment]
تست شد و مشکل قابل تکرار نبود
@Meysamhb

**Comment by Meysamhb** [comment]
فیلم مشکل در تلگرام ارسال شد
@pouryapb

**Comment by Meysamhb** [comment]
در هنگام اضافه کردن محصول(هر محصولی) به سبد خرید یک  باکس بدون پیغام (مطابق با عکس) ظاهر می شود و محصول به سبد خرید اضافه نمی شود
لازم به ذکر است با کاربر سوپرادمین این مشکل دیده نمی شود



![Image](https://github.com/sayyah/ECommerce/assets/92229790/08b81245-99a4-4a0f-8fa6-29df61ff1d9d)

@pouryapb

**Comment by sayyah** [comment]
کامنت

**Comment by pouryapb** [comment]
کامنت بک

**Comment by pouryapb** [comment]
مشکل رفع شد

**Comment by Meysamhb** [comment]
در هنگام پرداخت با درگاه زرین پال ارور " مشکلدر هنگام ثبت سفارش" می دهد
این ارور از این جهت مهم است  باید رفع شود که برای چک کردن موجودی و کم شدن تعداد در دیتابیس باید رفع شود تا مراحل تست به درستی انجام شود


![Image](https://github.com/sayyah/ECommerce/assets/92229790/fab17b40-62ab-45ef-8b8e-3808eeb568cd)

@pouryapb 
@sayyah

**Comment by pouryapb** [comment]
من قبل از پوش کردن تست کردم درگاه رو و پرداخت درست انجام شد. مراحل خاصی طی شد که به این ارور رسیدین؟
@Meysamhb

**Comment by Meysamhb** [comment]
نه مراحل خاصی طی نشد.با یک یوزر عادی درگاه زرین پال رو انتخاب کردم و بعد از زدن دمه ی "پرداخت موفق" صفحه ی مذکور نمایش داده شد

@pouryapb

**Comment by pouryapb** [comment]
![image](https://github.com/sayyah/ECommerce/assets/34511048/baa33682-495f-4c76-b78f-fa1aa95fa6e2)
برای من پرداخت انجام میشه

**Comment by Meysamhb** [comment]
در صفحه ی چک آوت هر آدرس جدیدی که میخواهیم ثبت کنیم با ارور ذزیر مواجه می شویم و همچنین در قسمت استان و شهر ،با انتخاب استان شهر آپدیت نمی شود

![Image](https://github.com/sayyah/ECommerce/assets/92229790/773e1ffe-5c52-4ba9-ad09-c19fbd8bc76b)

@pouryapb

**Comment by pouryapb** [comment]
انجام شد
@Meysamhb
